TILE_SIZE = 32
FPS = 60
WINDOW_WIDTH = 32 * TILE_SIZE
WINDOW_HEIGHT = 16 * TILE_SIZE

PLAYER_GRAVITY = 2
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 64
PLAYER_JUMP_STRENGTH = 20
PLAYER_SPEED = 5

MAX_FALLING_SPEED = 10

SPRITES_PATH = "src/Assets/images/"
LEVELS_PATH = "src/Assets/levels/lvl"

LEVEL_WIDTH = 128 * TILE_SIZE
LEVEL_HEIGHT = 16 * TILE_SIZE
STARTING_POS = (2*TILE_SIZE, WINDOW_HEIGHT - 2*TILE_SIZE)

